version: '3'

services:
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: "npm run dev"
    ports:
      - "3000:3000"

  backend:
    image: php:8.1-fpm
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    environment:
    - PHP_FPM_LISTEN=0.0.0.0:9000

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www
    depends_on:
      - backend
